
FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY backend ./backend

EXPOSE 8000

ENV MODULE_NAME="backend.server"
ENV VARIABLE_NAME="app"
ENV PORT="8000"

CMD ["uvicorn", "backend.server:app", "--host", "0.0.0.0", "--port", "8000"]
